x-image: &image
  ASTRA_LINUX: registry.astralinux.ru/library/alse:1.7.5

services:
  pg:
    build:
      context: /
      dockerfile: pg/Dockerfile
      args:
        <<: *image
        FP_USER: ${FP_USER}
        FP_REPO: ${FP_REPO}
        FP_REPO_SCHEMA: ${FP_REPO_SCHEMA}
        FP_USER_AUDIT: ${FP_USER_AUDIT}
        PG_LOG_STATEMENT: ${PG_LOG_STATEMENT}
    volumes:
      - pg_data:/var/lib/postgresql/11/main
    ports: 
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready"]
      interval: 5s
      retries: 5
      timeout: 30s
  redis:
    build:
      context: /
      dockerfile: redis/Dockerfile
      args:
        <<: *image
        SS_LOG_LEVEL: ${SS_LOG_LEVEL}
  bi:
    environment:
      - LSHOST
    build:
      context: /
      dockerfile: bi/Dockerfile
      args:
        <<: *image
        BI_PACKAGE: ${FP_PACKAGE}/foresight-fp${FP_RELEASE}.x-biserver*.deb
        BI_RM4_RES: ${FP_PACKAGE}/current.rm4
        BI_OPT_DIR: fp${FP_RELEASE}.x-biserver
        BI_CFG_DIR: fp${FP_RELEASE}.x-biserver/${BI_CFG_DIR:-bin}
        BI_ETC_DIR: apache2-fp${FP_RELEASE}.x
        BI_ETC_CTL: apache2ctl-fp${FP_RELEASE}.x
        BI_PORT: ${BI_PORT}
        FP_RELEASE: ${FP_RELEASE}
        FP_USER: ${FP_USER}
        FP_REPO: ${FP_REPO}
        FP_REPO_SCHEMA: ${FP_REPO_SCHEMA}
        FP_USER_AUDIT: ${FP_USER_AUDIT}
        DB_HOST: pg
        SS_HOST: redis
    ports: 
      - "${BI_PORT}:${BI_PORT}"
    links:
      - pg
      - redis
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_started
    configs:
      - repositories
  dba:
    build:
      context: /
      dockerfile: dba/Dockerfile
      args:
        <<: *image
        WEB_PACKAGE: ${FP_PACKAGE}/foresight-fp${FP_RELEASE}.x-webserver*.deb
        WEB_DBA_ZIP: ${FP_PACKAGE}/DBA.zip
        WEB_APP_DIR: fp${FP_RELEASE}.x-webserver
        WEB_DBA_DIR: fp${FP_RELEASE}.x-dba
        WEB_ETC_DIR: apache2-fp${FP_RELEASE}.x-web
        WEB_ETC_CTL: apache2ctl-fp${FP_RELEASE}.x-web
        WEB_APP_URI: fp${FP_RELEASE}.x
        WEB_PORT: ${WEB_PORT}
        FP_REPO: ${FP_REPO}
        FP_APP: ${FP_APP}
        BI_HOST: bi
        BI_PORT: ${BI_PORT}
        BI_SERVICE: FPBI_App_v${FP_RELEASE}.x/axis2/services/PP.SOM.Som
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    links:
      - bi
    depends_on:
      - bi
  scheduler:
    environment:
      - LSHOST
    build:
      context: /
      dockerfile: scheduler/Dockerfile
      args:
        <<: *image
        BI_PACKAGE: ${FP_PACKAGE}/foresight-fp${FP_RELEASE}.x-biserver*.deb
        BI_OPT_DIR: fp${FP_RELEASE}.x-biserver
        FP_USER: ${FP_USER}
        FP_REPO: ${FP_REPO}
        FP_REPO_SCHEMA: ${FP_REPO_SCHEMA}
        FP_USER_AUDIT: ${FP_USER_AUDIT}
        FP_CONTAINER_KEY: ${FP_CONTAINER_KEY}
        FP_CONTAINER_ID: ${FP_CONTAINER_ID}
        DB_HOST: pg
    links:
      - pg
    depends_on:
      - pg

volumes:
  pg_data:

configs:
  repositories:
    file: repos.yml