x-image: &image
  ASTRA_LINUX: registry.astralinux.ru/library/alse:1.7.5
x-license: &license
  LSHOST: 10.9.0.104
x-release: &release
  FP_PACKAGE: ${FP_PACKAGE}
  FP_RELEASE: ${FP_RELEASE}
x-repo: &repo
  FP_REPO: ${FP_REPO}
  FP_REPO_SCHEMA: ${FP_REPO_SCHEMA}
  FP_USER: ${FP_USER}
  FP_USER_AUDIT: ${FP_USER_AUDIT}

services:
  pg:
    build:
      context: /
      dockerfile: pg/Dockerfile
      args:
        <<: [*image,*repo]
        PG_LOG_STATEMENT: ${PG_LOG_STATEMENT}
    volumes:
      - pg_data:/var/lib/postgresql/11/main
    ports: 
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready"]
      interval: 5s
      retries: 5
      timeout: 30s
  redis:
    build:
      context: /
      dockerfile: redis/Dockerfile
      args:
        <<: *image
        SS_LOG_LEVEL: ${SS_LOG_LEVEL}
  bi:
    environment:
      <<: *license
    build:
      context: /
      dockerfile: bi/Dockerfile
      args:
        <<: [*image,*release,*repo]
        BI_PORT: ${BI_PORT}
        BI_PORT_WS: ${BI_PORT_WS}
        DB_HOST: pg
        #SS_HOST: redis
    ports: 
      - "${BI_PORT}:${BI_PORT}"
    links:
      - pg
      #- redis
    depends_on:
      pg:
        condition: service_healthy
    #  redis:
    #    condition: service_started
    configs:
      - repositories
  molap:
    environment:
      <<: *license
    build:
      context: /
      dockerfile: molap/Dockerfile
      args:
        <<: [*image,*release,*repo]
        BI_PORT: ${MOLAP_PORT}
        DB_HOST: pg
    volumes:
      - molap_data:/mnt/cache
    ports:
      - "${MOLAP_PORT}:${MOLAP_PORT}"
    links:
      - pg
    depends_on:
      pg:
        condition: service_healthy
    configs:
      - repositories
  dba:
    build:
      context: /
      dockerfile: dba/Dockerfile
      args:
        <<: [*image,*release]
        WEB_PORT: ${WEB_PORT}
        WEB_PORT_WS: ${WEB_PORT_WS}
        BI_HOST: bi
        BI_PORT: ${BI_PORT}
        BI_PORT_WS: ${BI_PORT_WS}
        FP_REPO: ${FP_REPO}
        FP_APP: ${FP_APP}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${WEB_PORT_WS}:${WEB_PORT_WS}"
    links:
      - bi
    depends_on:
      - bi
  scheduler:
    environment:
      <<: *license
    build:
      context: /
      dockerfile: scheduler/Dockerfile
      args:
        <<: *image
        BI_PACKAGE: ${FP_PACKAGE}/foresight-fp${FP_RELEASE}.x-biserver*.deb
        BI_OPT_DIR: fp${FP_RELEASE}.x-biserver
        BI_CFG_DIR: fp${FP_RELEASE}.x-biserver/${BI_CFG_DIR:-bin}
        FP_RELEASE: ${FP_RELEASE}
        FP_USER: ${FP_USER}
        FP_USER_2: ${FP_USER_2}
        FP_REPO: ${FP_REPO}
        FP_REPO_SCHEMA: ${FP_REPO_SCHEMA}
        FP_USER_AUDIT: ${FP_USER_AUDIT}
        FP_CONTAINER_KEY: ${FP_CONTAINER_KEY}
        FP_CONTAINER_ID: ${FP_CONTAINER_ID}
        DB_HOST: pg
    links:
      - pg
    depends_on:
      - pg
  desktop:
    environment:
      <<: *license
    build:
      context: /
      dockerfile: desktop/Dockerfile
      args:
        <<: [*image,*release]
        RDP_PORT: ${RDP_PORT}
    configs:
      - repositories

volumes:
  pg_data:
  molap_data:

configs:
  repositories:
    file: repos.yml